# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            itech.expert
tagline:          Yet another blog on software development
url:              http://itech.expert
paginate:         1
baseurl:          /
author:
  name:           Oscar Castro
  url:            http://itech.expert
  email:          oscar.castro@itech.expert

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
